AaronGarcia97/CodeU-Spring-2018-T9

- src/main/webapp/WEB-INF/appengine-web.xml
I just added our **project id *t9-laaph*** so we can connect our project to the cloud engine.
> Set project id t9-laaph

- src/main/webapp/index.jsp
Added Team Name & introduced what LAAPH stands for
> Added Team Name to index.jsp

- src/main/webapp/about.jsp
Modified about.jsp so that it shows team information.
> about.jsp modification

- src/main/java/codeu/controller/ProfileServlet.java
- src/main/webapp/WEB-INF/view/chat.jsp
- src/main/webapp/WEB-INF/view/profile.jsp
- src/main/webapp/WEB-INF/web.xml
- src/test/java/codeu/controller/ProfileServletTest.java
-In ProfileServlet class, create valid profile page for existing users (such as users/anita if Anita registered) 
-Forward to profile.jsp to display “Welcome to Anita’s Page!”
-Map ProfileServlet class to the URL users/* (where * can be followed by any username)
-Modified chat.jsp to link the author’s name in conversation to their profile page
> Created prototype for profile page feature

- src/main/java/codeu/model/store/basic/ConversationStore.java
- src/main/java/codeu/model/store/basic/MessageStore.java
- src/main/java/codeu/model/store/basic/UserStore.java
- src/main/webapp/WEB-INF/view/admin.jsp
- src/test/java/codeu/model/store/basic/ConversationStoreTest.java
- src/test/java/codeu/model/store/basic/MessageStoreTest.java
- src/test/java/codeu/model/store/basic/UserStoreTest.java
- Added new function in each datastore(users, messages, conversations) that retrieves the size of each.
- Called each function and assigned the returning integer to its corresponding size.
- Displayed sizes in the front end
- Created tests for each datastore function created
> Showing simple/basic statistics in admin page

- src/test/java/codeu/controller/ActivityFeedServletTest.java
-Adds test for the activity feed servlet
These servlet tests are what i'm the most uncertain in, so please critique anything that seems the least bit off! Thanks.
> Padraic development

- src/main/webapp/WEB-INF/view/navbar.jsp
- Added '/' in front of Profile href attribute.
> Fixed user infinitely appending

- src/main/java/codeu/controller/ProfileServlet.java
- src/main/webapp/WEB-INF/view/chat.jsp
- src/main/webapp/WEB-INF/view/profile.jsp
- src/test/java/codeu/controller/ProfileServletTest.java
-In chat.jsp: generates URL with username directly after /users/
-In ProfileServlet.java: extracts username from URL & moved some logic originally from profile.jsp to ProfileServlet.java: checks if profile page requested is valid user and prints error statement if profile page requested is not a valid user
-In ProfileServletTest.java: since modified ProfileServlet, modified Test for invalid user to not forward request/response to profile.jsp
>  Display errors as print statements in ProfileServlet.java and uses string parsing to get username from URL

- src/main/java/codeu/controller/UserVerificationServlet.java
- src/main/webapp/WEB-INF/view/login.jsp
- src/main/webapp/WEB-INF/view/userVerification.jsp
- src/main/webapp/WEB-INF/web.xml
- src/test/java/codeu/controller/UserVerificationTest.java
created verification page. currently does not does not take user input.
> adding basics for verification page

- src/main/webapp/WEB-INF/view/activityfeed.jsp
- src/main/webapp/WEB-INF/view/chat.jsp
- src/main/webapp/WEB-INF/view/chatbox.jsp
*activityfeed.jsp
--format changed to reflect chat.jsp
--added functionality for retrieving and displaying messages from the activity feed conversation
*chat.jsp
--Modified so that the message storage box's format is pulled in from chatbox.jsp, so that activityfeed and chat share the same source
*chatbox.jsp
--Created so that activityfeed and chat contain the same source code in regard to formatting the message container
> Modifies activityfeed.jsp so that it resembles the format of chat.jsp and can display messages

- src/main/java/codeu/controller/RegisterServlet.java
- src/main/java/codeu/model/data/User.java
- src/main/java/codeu/model/store/persistence/PersistentDataStore.java
- src/test/java/codeu/controller/AdminServletTest.java
- src/test/java/codeu/controller/ChatServletTest.java
- src/test/java/codeu/controller/ConversationServletTest.java
- src/test/java/codeu/controller/LoginServletTest.java
- src/test/java/codeu/controller/ProfileServletTest.java
- src/test/java/codeu/model/data/UserTest.java
- src/test/java/codeu/model/store/basic/UserStoreTest.java
- src/test/java/codeu/model/store/persistence/PersistentDataStoreTest.java
- src/test/java/codeu/model/store/persistence/PersistentStorageAgentTest.java
- Stored the boolean attribute as String in the datastore and when I retrieve it I turn it back to a Boolean.
- Added method `isAdmin()`.
- Modified a bunch of tests and added admin attribute to User class.
> Added admin attribute

- src/test/java/codeu/controller/AdminServletTest.java
- `testDoPost_UserDoesNotExist()`
- `testDoPost_UserIsAlreadyAdmin()`
- `testDoPost_MakeUserAdmin()`
- `testDoGet_ValidAdminUser()`
- `testDoGet_NotAdminUser()`
> AdminServlet Tests Done

- src/main/webapp/WEB-INF/view/navbar.jsp
- src/main/webapp/WEB-INF/view/profile.jsp
- src/main/webapp/css/main.css
-Small commits // just making profile page look better
-Displays user's bio after user submits form automatically
-Added h2 and h3 in main.css with different shades of blue for profile page
> Displays user's bio after editing + added colors to headers in main.css

- src/main/java/codeu/controller/ProfileServlet.java
- src/main/java/codeu/model/data/Conversation.java
- src/main/java/codeu/model/data/Message.java
- src/main/java/codeu/model/store/basic/MessageStore.java
- src/main/java/codeu/model/store/persistence/PersistentDataStore.java
- src/main/webapp/WEB-INF/view/profile.jsp
- src/test/java/codeu/model/store/basic/MessageStoreTest.java
- MessageStore.java: added method to retrieve only the messages sent by a certain user by iterating through all the Messages and only selecting those where the author id matches the author id argument sent in
- ProfileServlet.java: calls the method to retrieve user's sent messages and forwards that list of messages to profile.jsp
- profile.jsp: displays the sent messages on the user's profile page, converted Instant time to local date time object, changed colors of headers to sky blue and light blue.
> Displays users' sent messages on their profile page.

- src/main/java/codeu/model/data/Activity.java
- src/test/java/codeu/model/data/ActivityTest.java
Tests the accessors and constructor of the activity class
> Test for the activity class

- src/main/java/codeu/model/data/Activity.java
- src/test/java/codeu/model/data/ActivityTest.java
*Adds new class that will store activity feed data
* Adds new "count" parameters, which will help me figure out what conversations are trending/popular
> Added a new class that will assist in storing/retrieving data for the activity feed

- src/main/java/codeu/model/data/User.java
- src/main/webapp/WEB-INF/view/chat.jsp
- src/main/webapp/WEB-INF/view/conversations.jsp
- src/main/webapp/WEB-INF/view/login.jsp
- src/main/webapp/WEB-INF/view/newPassword.jsp
- src/main/webapp/WEB-INF/view/register.jsp
- Added `getTime()` which returns user creation `Instant` in a readable `String` format, to be later showed in Admin stats.
- Added js code to almost every `.jsp` file, so that every user input gets focused so that the user doesn't has to click it. 
**(It was a real headache having to click the user input textbox each time I wanted to test a feature) 😆
> Added User readable time and focus to every user input

- src/main/java/codeu/controller/AdminServlet.java
- src/main/java/codeu/model/store/basic/ConversationStore.java
- src/main/java/codeu/model/store/basic/MessageStore.java
- src/main/java/codeu/model/store/basic/UserStore.java
- src/test/java/codeu/model/store/basic/ConversationStoreTest.java
- src/test/java/codeu/model/store/basic/MessageStoreTest.java
- src/test/java/codeu/model/store/basic/UserStoreTest.java
- Added latest User retrieval
- Added latest Conversation retrieval
- Added latest Message retrieval
** All of these objects where put into the map that I will be sending as the request attribute.
- Added Test for getLatestUser
- Added Test for getLatestConversation
- Added Test for get LatestMessage
**After this PR is approved, I will display them in the `admin.jsp` file. (Didn't doit in this PR to keep it small-sized)
In the future I'm looking forward to reduce the lines of code used in the `addStats()` function in `AdminServlet.java` by refactoring it.
> Added 3 more stats Latest(User + Conversation + Message)

- src/main/java/codeu/controller/AdminServlet.java
- src/main/webapp/WEB-INF/view/admin.jsp
- Last User created name and date, with `href` to their profile.
- Last Conversation created name and date, with `href` to the conversation.
- Last Message created, content, by whom, and date, with `href` to sender profile.
**NOTE: If there's no lastUser, lastConv or lastMessage, a blank space will be printed in the corresponding fields!
> Displayed new stats!

- src/main/webapp/WEB-INF/view/admin.jsp
- A link was being redirected to a wrong directory!
> Fixed a href /conversations/ -> /chat/

- src/main/java/codeu/controller/NewPasswordServlet.java
- src/main/webapp/WEB-INF/view/newPassword.jsp
- src/test/java/codeu/controller/NewPasswordServletTest.java
Password must be between 5 and 12 characters and contain both letters and numbers.
> Password restrictions done

- src/main/java/codeu/model/store/basic/ConversationStore.java
- src/main/java/codeu/model/store/persistence/PersistentDataStore.java
- src/main/java/codeu/model/store/persistence/PersistentStorageAgent.java
Deleted the remains of the old activity feed system from a few files.
> Cleaning out the last vestiges of the old activity feed system

- src/main/java/codeu/controller/ConversationServlet.java
- src/main/java/codeu/model/data/User.java
- src/main/java/codeu/model/store/basic/ConversationStore.java
- src/main/java/codeu/model/store/persistence/PersistentDataStore.java
- src/main/java/codeu/model/store/persistence/PersistentStorageAgent.java
- src/main/webapp/WEB-INF/view/profile.jsp
- src/test/java/codeu/model/store/persistence/PersistentDataStoreTest.java
- src/test/java/codeu/model/store/persistence/PersistentStorageAgentTest.java
User.java:
-added ArrayList<String> pals to keep track of the User's list of pals
-added ArrayList<String> incomingRequests to keep track of the list of users who sent this User a pal request
-added ArrayList<String> outgoingRequests to keep track of the list of users this User sent a pal request to
*Note: incomingRequests and outgoingRequests don't do anything yet; just added these for the next set of commits
ConversationStore.java:
-removed restrictedConversationNames b/c modified private conversations to be /chat/user1&user2 and users cannot use "&" (only letters and numbers) when making their own conversation name, so this "&" will distinguish between two users and make it restricted [only created automatically for private conversations]
profile.jsp:
-only display "view conversation …
> Added "&" between /chat/user1&user2 and working on list of User's pals

- src/main/java/codeu/controller/ConversationServlet.java
- src/main/webapp/WEB-INF/view/activityfeed.jsp
*ConversationServlet.java
++Changed the message stored in Conversation activities to work with the new format in the activity feed.
*activityfeed.jsp
++Added logic to differentiate between conversation and registration type activities
++conversation and registration type activities displayed slightly differently in the activity feed
> Changed display in the activity feed to provide links for conversations

- src/main/java/codeu/controller/AjaxGetMessages.java
- src/main/java/codeu/model/data/AjaxMessage.java
- src/main/webapp/WEB-INF/view/chat.jsp
* Newly appended messages now
- show author name instead of author uuid (weird large number)
- now link to user profile when clicked
- show hour when message was sent
* Every message shows hour when message was sent as well.
* Created `codeu.model.data.AjaxMessage` file, that is a modified version of Message.
> New messages now show author name and also added timeframe to every message

- src/main/java/codeu/controller/AdminServlet.java
- src/main/java/codeu/controller/ChatServlet.java
- src/main/java/codeu/controller/ProfileServlet.java
- src/main/java/codeu/model/data/Conversation.java
- src/main/java/codeu/model/data/Message.java
- src/main/java/codeu/model/data/User.java
- src/main/java/codeu/model/data/Utils.java
- src/main/webapp/WEB-INF/view/profile.jsp
- src/main/webapp/css/main.css
- src/test/java/codeu/controller/ProfileServletTest.java
ProfileServletTest.java:
- Added 3 tests for sendPalRequest(), acceptPal(), and declinePal() in ProfileServlet.java
Utils.java:
- Added static getTime() function (instead of repeating method in User.java, Message.java, Conversation.java): modified AdminServlet.java to use new Utils.java
ChatServlet.java:
- Calls createConversations() if the private conversation has not been generated for two users because they were created before this feature was implemented (fixes for old users)
- If the conversation is private, only allows user to view if they are currently logged in as one of the two users in the conversation; else will print out message that they cannot view this conversation and redirect the user back to conversations/ link
ProfileServlet.java + profile.jsp:
- Displays list of pals …
> Added tests in ProfileServletTest.java and display list of pals, incomingRequests, outgoingRequests on user profile page

- pom.xml
- src/main/java/codeu/controller/ForgotPasswordServlet.java
- src/main/java/codeu/controller/NewPasswordServlet.java
- src/main/java/codeu/controller/RegisterServlet.java
- src/main/java/codeu/controller/ServerStartupListener.java
- src/main/java/codeu/model/data/Mail.java
- src/main/java/codeu/model/data/User.java
- src/main/java/codeu/model/store/basic/UserStore.java
- src/main/java/codeu/model/store/persistence/PersistentDataStore.java
- src/main/webapp/WEB-INF/view/forgotPassword.jsp
- src/main/webapp/WEB-INF/view/login.jsp
- src/main/webapp/WEB-INF/view/navbar.jsp
- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/index.jsp
- src/test/java/codeu/controller/AdminServletTest.java
- src/test/java/codeu/controller/ChatServletTest.java
- src/test/java/codeu/controller/ConversationServletTest.java
- src/test/java/codeu/controller/LoginServletTest.java
- src/test/java/codeu/controller/NewPasswordServletTest.java
- src/test/java/codeu/controller/ProfileServletTest.java
- src/test/java/codeu/controller/RegisterServletTest.java
- src/test/java/codeu/model/data/UserTest.java
- src/test/java/codeu/model/store/basic/UserStoreTest.java
- src/test/java/codeu/model/store/persistence/PersistentDataStoreTest.java
- src/test/java/codeu/model/store/persistence/PersistentStorageAgentTest.java
email feature and modified access when logged out
> Lee roys development

- src/main/java/codeu/controller/ChatServlet.java
*ChatServlet.java
++Private conversations no longer search for (and try to update) a non-existent Activity object associated with a private conversation.
> Fixed nullpointer exception error when posting in private conversations

- src/main/java/codeu/model/data/User.java
- src/main/java/codeu/model/data/Utils.java
- src/main/webapp/WEB-INF/view/chat.jsp
- src/main/webapp/WEB-INF/view/conversations.jsp
- src/main/webapp/WEB-INF/view/navbar.jsp
- src/main/webapp/WEB-INF/view/profile.jsp
- src/main/webapp/about.jsp
- src/main/webapp/css/main.css
- src/main/webapp/index.jsp
Utils.java:
- added getPrivateConversationURL() method that takes 2 usernames and returns the conversation URL of those names in alphabetical order (to avoid repeating code)
conversations.jsp:
- added user's list of private conversations/direct messages if they are logged in
navbar.jsp:
- simplified the logic
- moved Admin and Logout to right side of navigation bar
main.css:
- designed frontend website style/colors/fonts
about.jsp:
- added links to team members' profile pages
- fixed italics to be consistent
> Designed frontend website style/colors/fonts & added direct messages to Conversations tab

- src/main/java/codeu/controller/ServerStartupListener.java
- src/main/webapp/about.jsp
Fixed an error that was most likely preventing me from deploying to the web server. Shouldn't be any other changes besides that.
Also changed our about page to our showcase description along with our meet the team blurb instead of the "about codeu" description we never took down.
> Fixing error preventing deployment to web server
